name: Lint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Fixes: https://github.com/actions/checkout/issues/135
    - name: Set git to use LF.
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Install dependencies.
      run: sudo apt-get install -y clang-format
    - name: Lint
      run: make check